name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
        sudo apt-get update -qq
        sudo apt-get install libgl1-mesa-dev libsdl2-dev
    - name: Install premake
      run: |
         wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-linux.tar.gz -O premake.tar.gz
         tar -xf premake.tar.gz
    - name: Run premake
      run: |
        ./premake5 gmake
    - name: Build
      run: |
        cd build
        make config=release_x86_64
    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: renderer_bgfx_x86_64
        path: build/bin_x64/renderer_bgfx_x86_64.so

  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with: 
        msystem: MINGW32
        update: true
        install: base-devel mingw-w64-i686-gcc
    - name: Clone ioquake3
      shell: cmd
      run: |
        git clone https://github.com/ioquake/ioq3.git ../ioq3
    - name: Run premake
      shell: powershell
      run: |
        .\bin\premake5.exe gmake
    - name: Build
      shell: msys2 {0}    
      run: |
        cd build
        make
    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: renderer_bgfx_x86
        path: build\bin_x86\renderer_bgfx_x86.dll
